name: 'pr-agent-rs'
description: 'Summarize, review and suggest improvements for pull requests (Rust)'
branding:
  icon: 'award'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile.github_action'
